name: Build .deb Package

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ubuntu-24.04

    steps:
      - uses: actions/checkout@d632683dd7b4114ad314bca15554477dd762a938  # v4.2.0

      - name: Install build dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y debhelper-compat python3-setuptools python3-all pybuild-plugin-pyproject

      - name: Build .deb package
        run: |
          dpkg-buildpackage -us -uc -b

      - name: Upload to Release
        uses: softprops/action-gh-release@de2c0eb89ae2a093876385947365ebb7e0ef5c45  # v1.8.0
        with:
          files: ../clipmanx_*.deb
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
